# Default values for algon.

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  hosts:
    - host: algon.local
      paths:
        - "/"
  tls: []

algorand:
  network: testnet
  config:
    algod:
      Version: 33
      BaseLoggerDebugLevel: 3
      DNSSecurityFlags: 0
      LogArchiveMaxAge: "1h"
      LogArchiveName: "node.archive.log"
      LogSizeLimit: 0
      NodeExporterListenAddress: ":9100"
      NodeExporterPath: "./node_exporter"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/activadigital-it/algon
  # Defaults to Chart appVersion
  # tag:
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # privileged: false
  # readOnlyRootFilesystem: true
  # allowPrivilegeEscalation: false
  # runAsUser: 10001
  # runAsGroup: 10001
  # capabilities:
  #   drop:
  #   - ALL
  # seccompProfile:
  #   type: RuntimeDefault

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

storage:
  size: 50Gi
