apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskname: {{ $fullName }}-data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
      