{{- $fullName := include "algon.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algon-data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
      